# GET http://localhost:3003/api/patients

# POST http://localhost:3003/api/patients
# Content-Type: application/json

# {
#     "name": "Mary Patient",
#     "dateOfBirth": "1975-05-25",
#     "ssn": "300179-77C",
#     "gender": "female",
#     "occupation": "developer"
# }

# GET http://localhost:3003/api/patients/2


POST http://localhost:3003/api/patients/2/entries
Content-Type: application/json

{
    "type": "Hospital",
    "description": "Coding Rage",
    "diagnosisCodes": ["S62.5"],
    "specialist": "MD House",
    "date": "2015-01-02"
}