# GET http://localhost:3003/api/patients

POST http://localhost:3003/api/patients
Content-Type: application/json

{
    "name": "John Patient",
    "dateOfBirth": "1980-05-25",
    "ssn": "300179-77B",
    "gender": "male",
    "occupation": "developer",
}